import {
  XMarkIcon,
  TrashIcon,
  MagnifyingGlassIcon,
  PencilIcon,
  Bars3Icon,
  Bars2Icon,
  GlobeAltIcon,
  DevicePhoneMobileIcon,
  ComputerDesktopIcon,
  CheckCircleIcon,
  FireIcon,
  BriefcaseIcon,
  ChartBarIcon,
  ClockIcon,
  CubeIcon,
  SpeakerWaveIcon,
  SpeakerXMarkIcon,
  MoonIcon,
  SunIcon,
  TvIcon,
  Cog6ToothIcon,
  PlayCircleIcon,
  ArrowPathIcon,
  PlusCircleIcon,
} from "@heroicons/vue/16/solid";

export const icons = {
  clear: XMarkIcon,
  close: XMarkIcon,
  plus: PlusCircleIcon,
  app: CubeIcon,
  done: CheckCircleIcon,
  web: GlobeAltIcon,
  mobile: DevicePhoneMobileIcon,
  desktop: ComputerDesktopIcon,
  pending: PlayCircleIcon,
  inProgress: ArrowPathIcon,
  menu: Bars3Icon,
  drag: Bars2Icon,
  trash: TrashIcon,
  edit: PencilIcon,
  search: MagnifyingGlassIcon,
  category: BriefcaseIcon,
  priority: FireIcon,
  status: ChartBarIcon,
  clock: ClockIcon,
  soundOn: SpeakerWaveIcon,
  soundOff: SpeakerXMarkIcon,
  dark: MoonIcon,
  light: SunIcon,
  system: TvIcon,
  settings: Cog6ToothIcon,
};
