import {
  PlusIcon,
  XMarkIcon,
  TrashIcon,
  MagnifyingGlassIcon,
  ChevronDoubleDownIcon,
  ChevronDoubleUpIcon,
  NumberedListIcon,
  PencilIcon,
  Bars3Icon,
  Bars2Icon,
  GlobeAltIcon,
  DevicePhoneMobileIcon,
  ComputerDesktopIcon,
  CheckCircleIcon,
  MinusCircleIcon,
  EllipsisHorizontalCircleIcon,
  XCircleIcon,
} from "@heroicons/vue/24/outline";

export const icons = {
  cancel: XCircleIcon,
  logo: NumberedListIcon,
  web: GlobeAltIcon,
  mobile: DevicePhoneMobileIcon,
  desktop: ComputerDesktopIcon,
  pending: MinusCircleIcon,
  inProgress: EllipsisHorizontalCircleIcon,
  done: CheckCircleIcon,
  plus: PlusIcon,
  menu: Bars3Icon,
  drag: Bars2Icon,
  xmark: XMarkIcon,
  trash: TrashIcon,
  pencil: PencilIcon,
  search: MagnifyingGlassIcon,
  arrowUp: ChevronDoubleUpIcon,
  arrowDown: ChevronDoubleDownIcon,
};
