import {
  PlusIcon,
  XMarkIcon,
  TrashIcon,
  MagnifyingGlassIcon,
  PencilIcon,
  Bars3Icon,
  Bars2Icon,
  GlobeAltIcon,
  DevicePhoneMobileIcon,
  ComputerDesktopIcon,
  CheckCircleIcon,
  XCircleIcon,
  FireIcon,
  BriefcaseIcon,
  ChartBarIcon,
  ClockIcon,
  CubeIcon,
  SpeakerWaveIcon,
  SpeakerXMarkIcon,
  MoonIcon,
  SunIcon,
  TvIcon,
  Cog6ToothIcon,
  PlayCircleIcon,
  ChevronRightIcon,
  ChevronDoubleRightIcon,
  ArrowPathIcon,
} from "@heroicons/vue/16/solid";

export const icons = {
  appName: CubeIcon,
  done: CheckCircleIcon,
  cancel: XCircleIcon,
  web: GlobeAltIcon,
  mobile: DevicePhoneMobileIcon,
  desktop: ComputerDesktopIcon,
  pending: PlayCircleIcon,
  inProgress: ArrowPathIcon,
  plus: PlusIcon,
  menu: Bars3Icon,
  drag: Bars2Icon,
  close: XMarkIcon,
  trash: TrashIcon,
  edit: PencilIcon,
  search: MagnifyingGlassIcon,
  category: BriefcaseIcon,
  priority: FireIcon,
  status: ChartBarIcon,
  clock: ClockIcon,
  soundOn: SpeakerWaveIcon,
  soundOff: SpeakerXMarkIcon,
  dark: MoonIcon,
  light: SunIcon,
  system: TvIcon,
  settings: Cog6ToothIcon,
};
