import { createI18n } from "vue-i18n";

export const messages = {
  en: {
    labels: {
      search: "Search...",
      category: "Category",
      priority: "Priority",
      status: "Status",
      appName: "App name",
      appType: "App type",
      taskName: "Name",
    },
    buttons: {
      createTask: "Create task",
      createApp: "Add application",
      update: "Save",
      yes: "Yes",
      no: "No",
      resetFilters: "Reset filters",
    },
    priority: {
      critical: "Critical",
      high: "High",
      medium: "Medium",
      low: "Low",
      optional: "Optional",
    },
    status: {
      pending: "Pending",
      inProgress: "In Progress",
      done: "Done",
    },
    category: {
      frontend: "Frontend",
      backend: "Backend",
      database: "Database",
      devops: "DevOps",
      testing: "Testing",
      security: "Security",
      ux: "UX",
      integration: "Integration",
      product: "Product",
      analytics: "Analytics",
      marketing: "Marketing",
    },
    appType: {
      desktop: "Desktop",
      mobile: "Mobile",
      web: "Web",
    },
    errors: {
      emptyName: "Enter app name.",
      shortName: "App name must be at least 3 characters.",
    },
    noApps: "You don't have any tracking apps.",
    noTasks: "You don't have any tasks.",
    noResults: "No results.",
    removeQuestion: "Are you really want remove tracking",
  },
  ru: {
    labels: {
      search: "Поиск...",
      category: "Категория",
      priority: "Приоритет",
      status: "Статус",
      appName: "Название",
      appType: "Тип приложения",
      taskName: "Название",
    },
    buttons: {
      createTask: "Создать задачу",
      createApp: "Добавить приложение",
      update: "Сохранить",
      yes: "Да",
      no: "Нет",
      resetFilters: "Сбросить фильтры",
    },
    priority: {
      critical: "Критично",
      high: "Высокий",
      medium: "Средний",
      low: "Низкий",
      optional: "Необязательный",
    },
    status: {
      pending: "В ожидании",
      inProgress: "В процессе",
      done: "Готово",
    },
    category: {
      frontend: "Фронтенд",
      backend: "Бэкенд",
      database: "База данных",
      devops: "DevOps",
      testing: "Тестирование",
      security: "Безопасность",
      ux: "UX",
      integration: "Интеграция",
      product: "Продукт",
      analytics: "Аналитика",
      marketing: "Маркетинг",
    },
    appType: {
      desktop: "Десктоп",
      mobile: "Мобильное",
      web: "Веб",
    },
    errors: {
      emptyName: "Введите название.",
      shortName: "Название должно быть не мeнee 3 символов.",
    },
    noApps: "У вас нет отслеживаемых приложений.",
    noTasks: "Список задач пуст.",
    noResults: "Ничего не найдено.",
    removeQuestion: "Вы действительно хотите удалить трекинг",
  },

  ua: {
    labels: {
      search: "Пошук...",
      category: "Категорія",
      priority: "Пріоритет",
      status: "Статус",
      appName: "Назва",
      appType: "Тип додатку",
      taskName: "Назва",
    },
    buttons: {
      createTask: "Створити задачу",
      createApp: "Додати застосунок",
      update: "Зберегти",
      yes: "Так",
      no: "Нi",
      resetFilters: "Скинути фільтри",
    },
    priority: {
      critical: "Критично",
      high: "Високий",
      medium: "Середній",
      low: "Низький",
      optional: "Необов’язковий",
    },
    status: {
      pending: "В очікуванні",
      inProgress: "В процесі",
      done: "Готово",
    },
    category: {
      frontend: "Фронтенд",
      backend: "Бекенд",
      database: "База даних",
      devops: "DevOps",
      testing: "Тестування",
      security: "Безпека",
      ux: "UX",
      integration: "Інтеграція",
      product: "Продукт",
      analytics: "Аналітика",
      marketing: "Маркетинг",
    },
    appType: {
      desktop: "Десктоп",
      mobile: "Мобільний",
      web: "Веб",
    },
    errors: {
      emptyName: "Введіть назву.",
      shortName: "Назва має бути не менше 3 символів.",
    },
    noApps: "У вас жодного відстежуваного застосунка.",
    noTasks: "Список задач пустий.",
    noResults: "Нічого не знайдено.",
    removeQuestion: "Ви дійсно бажаєте видалити трекинг",
  },
};

const i18n = createI18n({
  legacy: false,
  locale: "en",
  fallbackLocale: "en",
  messages,
});

export default i18n;
